apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - observability-kustomization.yaml
  - python-simple-app-namespace.yaml
  - python-simple-app-helmrelease.yaml
  - python-simple-app-image-repository.yaml
  - python-simple-app-image-policy.yaml
  - python-simple-app-image-automation.yaml
