apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: application-manifests
  namespace: flux-system
spec:
  interval: 1m
  # Replace with the repository URL and configure authentication in Flux,
  # if the repository is private. No credentials are stored here.
  url: https://github.com/mehboobsubani/python-simple-app
  ref:
    branch: main
  secretRef:
    name: github-token
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dockerhub-charts
  namespace: flux-system
spec:
  type: oci
  interval: 1m
  url: oci://registry-1.docker.io/mehb786
