apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: python-simple-app
  namespace: python-simple-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./deploy/helm/python-simple-app
      sourceRef:
        kind: GitRepository
        name: python-simple-app
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    image:
      # Set this to the image loaded into kind or to a registry image.
      repository: mehb786/python-simple-app
      tag: latest
      pullPolicy: IfNotPresent
    replicaCount: 1
    ingress:
      enabled: true
    otel:
      endpoint: http://alloy.observability.svc.cluster.local:4317
