apiVersion: v1
kind: Service
metadata:
  name: python-simple-app
  labels:
    app.kubernetes.io/name: python-simple-app
spec:
  selector:
    app.kubernetes.io/name: python-simple-app
  ports:
    - name: http
      port: 5000
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
