apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-simple-app
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/example/python-simple-app
    newName: python-simple-app
    newTag: dev
patches:
  - path: patch-kind.yaml
