apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: ">=9.0.0 <10.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    admin:
      user: admin
      password: admin
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
    service:
      type: NodePort
      nodePort: 30000
    persistence:
      enabled: false
    sidecar:
      datasources:
        enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Mimir
            type: prometheus
            access: proxy
            url: http://mimir-nginx.observability.svc.cluster.local/prometheus
            isDefault: true
            jsonData:
              httpMethod: POST
              timeInterval: 15s
          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo.observability.svc.cluster.local:3200
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.observability.svc.cluster.local
